name: Release kmsgrab aarch64

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        # 맨 뒤의 마침표(.)가 빠지면 에러 납니다. 현재 경로를 컨텍스트로 지정합니다.
        run: docker build -t kms-builder -f Dockerfile .

      - name: Compile inside Docker
        run: |
          # 사용자님의 Dockerfile 내 WORKDIR인 /build를 활용합니다.
          docker run --rm -v $(pwd):/build kms-builder \
          aarch64-linux-gnu-gcc -O3 -s -o kmsgrab_aarch64 kmsgrab.c \
          $(pkg-config --cflags --libs libdrm libpng) \
          -static -lpthread -lm -lz

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: kmsgrab_aarch64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
