name: Release kmsgrab aarch64

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Docker (Ubuntu 22.04 base)
        run: |
          docker build -t kms-builder -f Dockerfile
     
          docker run --rm -v $(pwd):/build kms-builder \
          aarch64-linux-gnu-gcc -O3 -s -o kmsgrab_aarch64 kmsgrab.c \
          $(pkg-config --cflags --libs libdrm libpng) \
          -static -lpthread -lm -lz

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: kmsgrab_aarch64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
